import type { Job } from "./types"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "editor with a sense for timing",
    company: "remy zee",
    avatar: "/remyzee.jpeg",
    location: "Remote",
    type: "Part-time",
    category: "Video Editing",
    salary: "",
    description:
      "looking for someone who just gets comedic pacing. punchlines, pauses, and that perfect beat before the laugh. if you live and breathe cuts that feel like jokes — let’s talk.",
    postedAt: "1 day ago",
    tags: ["editing", "comedy", "short-form"],
    requirements: [],
    responsibilities: [],
    benefits: [],
    companyDescription: "",
  },
  {
    id: "2",
    title: "youtube editor who wants to grow with a creator",
    company: "daniel mints",
    avatar: "/danielmints.jpg",
    location: "Remote",
    type: "Part-time",
    category: "Video Editing",
    salary: "",
    description:
      "i’m looking for an editor who’s obsessed with youtube — not just the craft, but the strategy. if you study retention graphs for fun and dream of hitting 1M subs, this is for you.",
    postedAt: "2 days ago",
    tags: ["youtube", "editing", "storytelling"],
    requirements: [],
    responsibilities: [],
    benefits: [],
    companyDescription: "",
  },
  {
    id: "3",
    title: "ugc creators wanted",
    company: "cluely",
    avatar: "/cluely.jpeg",
    location: "Remote",
    type: "Part-time",
    category: "UGC",
    salary: "",
    description:
      "we’re looking for fresh faces to make short-form videos about ai productivity tools. no huge following needed — just creativity, good lighting, and consistency.",
    postedAt: "3 days ago",
    tags: ["ugc", "creator", "content"],
    requirements: [],
    responsibilities: [],
    benefits: [],
    companyDescription: "",
  },
  {
    id: "4",
    title: "video editor for katiexsocials",
    company: "katiexsocials",
    avatar: "/katiexsocials.jpg",
    location: "Remote",
    type: "Part-time",
    category: "Video Editing",
    salary: "",
    description:
      "help edit personal brand videos — social, storytelling, creator economy topics. someone with taste, rhythm, and curiosity for how ideas spread online.",
    postedAt: "4 days ago",
    tags: ["editing", "tiktok", "brand"],
    requirements: [],
    responsibilities: [],
    benefits: [],
    companyDescription: "",
  },
  {
    id: "5",
    title: "social media manager who actually gets it",
    company: "gusto",
    avatar: "/gusto.jpeg",
    location: "San Francisco, CA",
    type: "Full-time",
    category: "Social Media",
    salary: "",
    description:
      "we’re not looking for a content scheduler — we want a strategist who understands culture. someone who can spot trends early, move fast, and make a b2b brand feel human.",
    postedAt: "5 days ago",
    tags: ["social media", "strategy", "marketing"],
    requirements: [],
    responsibilities: [],
    benefits: [],
    companyDescription: "",
  },
]
